title: "Aoni Festival"
subtitle: "Level Up to the Next Stage"
baseurl: "" # leave blank for GitHub Pages
url: "https://aoni27th-maker.github.io/aonisai.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# Navigation
header_pages:
  - index.md
  - about.md
  - history.md
  - lineup.md
  - contact.md

# Author / social links
author:
  name: "Aoni Festival"
  links:
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/aonifes.official/"
    - label: "X"
      icon: "fab fa-x-twitter"
      url: "https://x.com/aonifestival"
    - label: "TikTok"
      icon: "fab fa-tiktok"
      url: "https://www.tiktok.com/@aonifestival27th?_r=1&_t=ZS-92BSodIxBfI"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCl-TnDDbia7sRXtFcLyTDbg"

# Plugins (required for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

  path: /tags/
